version: '3'

services:
  nginx:
    build:
      context: ./lde/nginx

    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./www/errors:/etc/nginx/html
      - ../node_modules:/node_modules
    depends_on:
      - php

  php:
    build:
      context: ./lde/php-fpm
    
    volumes:
      - ./www:/var/www/html
